# Generated by Django 4.2 on 2025-10-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('years_of_experience', models.IntegerField()),
                ('profile_photo', models.ImageField(upload_to='teacher_photos/')),
            ],
        ),
    ]
